---
site_name: eccenca Markdown Sandbox
repo_url: https://github.com/eccenca/markdown-sandbox
edit_uri: ./edit/main/docs
markdown_extensions:
  - extra
  - smarty
  - sane_lists
  - codehilite
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_css:
  - assets/stylesheets/extra.css

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eccenca
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/eccenca
    - icon: fontawesome/brands/python
      link: https://pypi.org/search/?q=cmem-&o=
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eccenca