---
site_name: eccenca Markdown Sandbox
repo_url: https://github.com/eccenca/markdown-sandbox
edit_uri: ./edit/main/docs

markdown_extensions:
  - extra
  - smarty
  - sane_lists
  - codehilite
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: '#'
      baselevel: 1
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition

plugins:
  - search:
      lang: en
  - awesome-pages
  - macros
  - autolinks
  - glightbox
  - social:
      cards: true
  - tags:
      tags_file: develop/tags.md
  - git-revision-date-localized:
      enable_creation_date: true
  - git-revision-date-localized:
      type: timeago
  - redirects:
      redirect_maps:
        'cmem.md': 'automate/cmemc-command-line-interface/index.md'
  - swagger-ui-tag

theme:
  name: material

  palette:
    primary: grey
    accent: orange

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  icon:
    logo: logo
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eccenca
    # - icon: fontawesome/brands/docker
    # link: https://hub.docker.com/u/eccenca
    # - icon: fontawesome/brands/python
    #  link: https://pypi.org/search/?q=cmem-&o=
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eccenca
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - assets/stylesheets/extra.css

