[tool.poetry]
name = "markdown-sandbox"
version = "0.1.0"
description = "Testing Repository for Training Purpose"
authors = ["Sebastian Tramp <sebastian.tramp@eccenca.com>"]
readme = "README.md"
packages = [{include = "markdown_sandbox"}]

[tool.poetry.dependencies]
python = "^3.10"
mkdocs-material = "^8.5.3"
Pillow = "^9.2.0"
CairoSVG = "^2.5.2"
mike = "^1.1.2"
mkdocs-git-revision-date-localized-plugin = "^1.1.0"
mkdocs-awesome-pages-plugin = "^2.8.0"

[tool.poetry.group.dev.dependencies]
linkcheckmd = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
